name: "Test"

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9
      - name: Initialize Terraform
        run: |
          terraform init
        working-directory: terraform
      - name: Deploy Infrastructure
        run: |
          terraform apply \
            -input=false \
            -auto-approve
        working-directory: terraform
      - name: Invoke Lambda
        uses: ./
        with:
          function-name: InvokeTestLambda
      - name: Destroy Infrastructure
        if: always()
        run: |
          terraform apply \
            -input=false \
            -destroy \
            -auto-approve
        working-directory: terraform
